---
- hosts: windows
  tasks:
    - name: Copy a file
      win_copy:
         src: /home/dayanand/Downloads/httpd-2.2.25-win32-x86-openssl-0.9.8y(1).msi 
         dest: c:\
 
    - name: Install Apache2 
      win_msi:
         path: c:\httpd-2.2.25-win32-x86-openssl-0.9.8y(1).msi
      
